### PR TITLE
Bidi ordering

### LINKED ISSUE #23: Wrong rendering for mixed LTR/RTL text
Hello.
Thanks for creating this great library.

I have a problem with RTL text rendering. The order of runs gets reversed if there is LTR characters in the middle of RTL text.

Here is the sample text:
```
وَرَسُولِهِ وَإِنْ تُبْتُمْ فَلَكُمْ رُءُوسُ hello أَمْوَالِكُمْ لَا تَظْلِمُونَ وَلَا تُظْلَمُونَ ( 279 ) وَإِنْ كَانَ ذُو عُسْرَةٍ فَنَظِرَةٌ إِلَى مَيْسَرَةٍ
```

Current Output:
Image

Expected Output:
Image

I tried setting the `Direction` of `shaping.Input` to `di.DirectionRTL` but that didn't help.
Thank you.

### PR DESCRIPTION
**Pull request by benoitkugler**
Use `LineWrapper` to compute bidi visual index; also set the overall direction of the string.
Closes #23

### CODE REVIEW

**Comment by benoitkugler** [comment]
Not sure what is happening with the CI checks

File: render.go [hunk 1]
```diff
@@ -51,6 +53,16 @@ func (r *Renderer) shape(str string, face *font.Face) (_ shaping.Line, ascent in
...
 	}
+
+	// overall direction of the text, deduced from the first runes
+	direction := line[0].Direction
+	r.wrapper.Prepare(shaping.WrapConfig{Direction: direction}, text, shaping.NewSliceIterator(line))
+	wrapped, _ := r.wrapper.WrapNextLine(math.MaxInt)
+	line = wrapped.Line
+
+	// sort the line by visual order
+	sort.Slice(line, func(i, j int) bool { return line[i].VisualIndex < line[j].VisualIndex })
```
Comment (whereswaldon) [inline render.go:64]: This is fine if we aren't going to do any processing that might rely on the logical ordering, but it is a lossy operation. After this sort, we no longer have easy access to the logical ordering.

In Gio's code, I just traverse the line's VisualOrder array when doing display logic. It's still efficient, but doesn't discard anything.

**Review by whereswaldon — APPROVED** [review]
I think these changes will work. There may be a "better" way to iterate the runs in-order, but the difference also might not matter for this use-case.

File: render.go (hunk 1 above)
Comment (benoitkugler) [reply render.go:64]: Acknowledged, thank you. We could apply your suggestion if required in future work.

**Comment by andydotxyz** [comment]
> Not sure what is happening with the CI checks

Ah, that's the x/tools Go version bug that was resolved by updating the tools package to `golang.org/x/tools v0.24.1`.
I know it's a transitive dependency here but if we can mark that version as required the CI should work.

(details at https://github.com/golang/go/issues/74462)

**Comment by benoitkugler** [comment]
> > Not sure what is happening with the CI checks
> 
> Ah, that's the x/tools Go version bug that was resolved by updating the tools package to `golang.org/x/tools v0.24.1`. I know it's a transitive dependency here but if we can mark that version as required the CI should work.
> 
> (details at [golang/go#74462](https://github.com/golang/go/issues/74462))

Thanks @andydotxyz ! Any hint on how to process to use v0.24.1 ?

**Comment by andydotxyz** [comment]
Can the go.mod be updated to require that version? Either the indirect section or through a replace.

I don't have an example to hand sorry as Fyne uses it directly so our fixes were more straight forward.

**Comment by whereswaldon** [comment]
Rebasd on top of the CI fix.

**Comment by benoitkugler** [comment]
@andydotxyz Would you like to have a glance at this PR ? It falls under the bug fix review policy, but since it introduces line wrapping in the render pipeline, I thought you might still want to review it.

**Comment by andydotxyz** [comment]
Apologies this slipped off the radar - been a tricky couple of weeks.

**Review by andydotxyz — APPROVED** [review]
Looks good.
Unless I've misunderstood this isn't adding wrapping at a user level but brings it in as a dependency only.

Future work will find a way to expose that through the API - though we need to think about the "first line" vs "other line" lengths as discussed in previous (non-render?) chat.
